routes/web.php
<?php
/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | This file is where you may define all of the routes that are handled
  | by your application. Just tell Laravel the URIs it should respond
  | to using a Closure or controller method. Build something great!
  |
 */

//Route::get('/', function () {
//     return view('welcome');
//});

Route::get('/', 'PostController@index');

Route::get('/blog', function() {
    return view('blog-home');
});

//Route::get('/posts/test', function() {
//    return view('blog-home');
//})->middleware('admin');


Route::resource('posts', 'PostController');

Route::resource('posts.comments', 'PostCommentController');

Route::resource('comments', 'CommentController');

Route::resource('users', 'UserController');

Route::resource('admin', 'AdminController');

// authentication routes
//Route::get('auth/login', 'Auth\AuthController@getLogin');
//Route::post('auth/login', 'Auth\AuthController@postLogin');
//Route::get('auth/logout', 'Auth\AuthController@getLogout');
// registration routes
//Route::get('auth/register', 'Auth\AuthController@getRegister');
//Route::post('auth/register', 'Auth\AuthController@postRegister');
//
//Route::controllers([
//    'password' => 'Auth\PasswordController'
//]);
Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/comments/create/{id}/{str}/', 'CommentController@store');

Route::post('/users/fileUpload/', 'UserController@fileUpload');

resources/views/app.blade.php
<html>
    <head>
        <title>Soulivong Blog</title>
    </head>
<body>
    <h2>Nav bar here</h2>
    @yield('content')
    <div class="footer">
        <h2>footer here</h2>
    </div>
</body>
</html>

resources/views/blog-home.blade.php
<h1>blog home</h1>  

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.basic.blade.php
@extends('app')
@section('content')
<h2>Home page</h2>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

<div class='container'>
    <style>
        #btnDelete{
            padding: 0px 0px 0px 0px
        }
        #pagination{
            text-align: center
        }
    </style>

    <div class='row'>
        @foreach($posts as $post)
        <div class="card">
            <div class="card-header">
                <h2>
                    <a href='{{ url('/posts', $post->id)}}'>
                        @if($admin)
                        {{$post->id}} | 
                        @endif 
                        {{$post->title}}
                    </a>

                </h2>
                <p>Created: <small>{{$post->created_at}}</small></p>
            </div>
            <div class="card-block">
                <p class="card-text">{{$post->body}}</p>
                <p><small>Author: 
                        <cite>{{$post->user->name}}</cite>
                    </small>
                </p>
                <p>Editted: <small>{{$post->updated_at}}</small></p>
                @if($admin)
                {!! Form::open(['method' => 'DELETE', 'route'=>['posts.destroy', $post->id], 'onsubmit' => 'return confirmDelete()']) !!}
                <a href='{{ route('posts.edit', $post->id)}}' class='btn btn-sm btn-warning'>edit</a>
                {!! Form::submit('delete', ['class' => 'btn btn-sm btn-danger']) !!}
                {!! Form::close() !!}
                @elseif(auth()->check() && auth()->user()->id == $post->user_id)
                {!! Form::open(['method' => 'DELETE', 'route'=>['posts.destroy', $post->id], 'onsubmit' => 'return confirmDelete()']) !!}
                <a href='{{ route('posts.edit', $post->id)}}'>edit</a> |
                {!! Form::submit('delete', ['class' => 'btn btn-link', 'id' => 'btnDelete']) !!}
                {!! Form::close() !!}
                @endif
            </div>
        </div>
        <br>
        @endforeach
        <div id='pagination'>
            {{ $posts->links() }}
        </div>
    </div>
</div>
<script>
    function confirmDelete() {
        var x = confirm('Are you sure you want to delete this post?');
        if (x) {
            return true;
        } else {
            return false;
        }
    }
</script>
@endsection